# Generated by Django 5.1.7 on 2025-04-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('restaurant_and_bar', 'Restaurant And Bar'), ('dhaba', 'Dhaba'), ('dhaba_with_liquor', 'Dhaba With Liquor'), ('cafe', 'Cafe')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
