# Generated by Django 5.2.1 on 2025-05-21 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0008_offer_delete_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='restaurant',
            field=models.ForeignKey(default=948739, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='qr.restaurant'),
            preserve_default=False,
        ),
    ]
