# Generated by Django 5.2.1 on 2025-05-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0010_liquortypes_liquor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
